export const GET_TIMELINE = 'GET_TIMELINE';
export const INIT_TIMELINE = 'INIT_TIMELINE';
export const GET_TIMELINE_FAIL = 'GET_TIMELINE_FAIL';

export const GET_PRODUCT_LIST = 'GET_PRODUCT_LIST';
export const GET_CONTACT_LIST = 'GET_CONTACT_LIST';
export const GET_FACILITY_PHOTOS = 'GET_FACILITY_PHOTOS';