export const GET_TIMELINE = 'GET_TIMELINE';
export const INIT_TIMELINE = 'INIT_TIMELINE';
export const GET_TIMELINE_FAIL = 'GET_TIMELINE_FAIL';

export const INIT_PRODUCT_DETAIL_LIST = 'INIT_PRODUCT_DETAIL_LIST';
export const GET_PRODUCT_DETAIL_LIST = 'GET_PRODUCT_DETAIL_LIST';
export const GET_PRODUCT_DETAIL_LIST_FAIL = 'GET_PRODUCT_DETAIL_LIST_FAIL';

export const INIT_PRODUCT_CATEGORY_LIST = 'INIT_PRODUCT_CATEGORY_LIST';
export const GET_PRODUCT_CATEGORY_LIST = 'GET_PRODUCT_CATEGORY_LIST';
export const GET_PRODUCT_CATEGORY_LIST_FAIL = 'GET_PRODUCT_CATEGORY_LIST_FAIL';

export const INIT_FACILITY_GALLERIES = 'INIT_FACILITY_GALLERIES';
export const GET_FACILITY_GALLERIES = 'GET_FACILITY_GALLERIES';
export const GET_FACILITY_GALLERIES_FAIL = 'GET_FACILITY_GALLERIES_FAIL';

export const INIT_CONTACT_LIST = 'INIT_CONTACT_LIST';
export const GET_CONTACT_LIST = 'GET_CONTACT_LIST';
export const GET_CONTACT_LIST_FAIL = 'GET_CONTACT_LIST_FAIL';
